# Generated by Django 4.2.26 on 2025-11-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floor_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='floor_plans/%Y/%m/')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_floor_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_floor_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoom',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('MEETING', 'Meeting Room'), ('CONFERENCE', 'Conference Room'), ('HUDDLE', 'Huddle Space'), ('PHONE_BOOTH', 'Phone Booth')], default='MEETING', max_length=20)),
                ('capacity', models.IntegerField()),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_video_conference', models.BooleanField(default=False)),
                ('has_tv_monitor', models.BooleanField(default=False)),
                ('has_premium_audio', models.BooleanField(default=False)),
                ('has_natural_light', models.BooleanField(default=False)),
                ('has_kitchen_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('floor_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='floors.floorplan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical room',
                'verbose_name_plural': 'historical rooms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFloorPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floor_number', models.IntegerField()),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical floor plan',
                'verbose_name_plural': 'historical floor plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_a', models.JSONField()),
                ('changes_b', models.JSONField()),
                ('version_at_conflict', models.IntegerField()),
                ('resolved_data', models.JSONField()),
                ('resolution_strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='floors.floorplan')),
                ('user_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_as_user_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_as_user_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('MEETING', 'Meeting Room'), ('CONFERENCE', 'Conference Room'), ('HUDDLE', 'Huddle Space'), ('PHONE_BOOTH', 'Phone Booth')], default='MEETING', max_length=20)),
                ('capacity', models.IntegerField()),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_video_conference', models.BooleanField(default=False)),
                ('has_tv_monitor', models.BooleanField(default=False)),
                ('has_premium_audio', models.BooleanField(default=False)),
                ('has_natural_light', models.BooleanField(default=False)),
                ('has_kitchen_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='floors.floorplan')),
            ],
            options={
                'indexes': [models.Index(fields=['capacity'], name='floors_room_capacit_51b331_idx'), models.Index(fields=['is_active'], name='floors_room_is_acti_8770ef_idx')],
                'unique_together': {('floor_plan', 'room_number')},
            },
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['floor_number'], name='floors_floo_floor_n_01dcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['version'], name='floors_floo_version_979d71_idx'),
        ),
    ]
